### ISSUE TITLE
看完了doc，说说个人看法

### ISSUE THREAD

**Issue by Frodez** [TangBean/OnlineExecutor#10]
我只能写java，java写得也不咋样，编译原理什么都不懂，所有的基础课程也没学过，会的只有CURD。
感觉想法其实挺好的，调用jdk系统类库进行编译，然后hack一部分调用，里面涉及的java知识只是听过却没写过，所以佩服。
不过有个很麻烦的问题，你只hack了System，同时又没有屏蔽太多的功能，那么用户要是不写System.out.println怎么办呢？jdk里功能太多了。用户可以用jdk发起很多系统调用的，比如shell。
那么用户其实完全可以调用shell，然后尝试找到javac，再编译，再执行。
这只是其中的一小部分，还有很多事情可以做。
不过前面有关字节码的知识，有关jdk vm相关类库的知识让我受益良多，所以还是非常感谢。

**Comment by TangBean** [comment]
感谢看完了 doc，今年春节的时候花了好些时间写的（其实写 doc 的时间远大于 coding 的时间了），能有人认真的看完还是很开心的。
事情是这样的，我写这个项目的动机并不是想实现一个在线的 Java IDE，而是因为看了《深入理解 Java 虚拟机》的第九章，觉得书中提的那个修改字节码的技术特酷，就像用这个写点什么，就写了这个项目。
所以老实讲，这并不是实现一个在线 Java IDE 的最好选择，只是我觉得这个技术好像可以拿来干这个而已，这也就导致你说的那些问题哈。
可以把这个项目当成学习性质的项目来看哈，用来学习一些平时不常用到，但可以帮助我们更好的理解 Java 程序的运行~
